prepareSql <-
function(dbms, ..., inputFile = NULL, outputFile = NULL) {
    parameter <- list(...)

    if(is.null(inputFile))
        inputFile <- system.file("sql", "ald-mannheim-no-hepatitis.sql", package="AlcoholicLiverDisease", mustWork=TRUE)

    if(is.null(outputFile))
        outputFile <- file.path(tempdir(), sprintf("ald_mannheim_survival_autogenerated_%s_%s.sql", dbms, parameter[["studyName"]]))

    parameterizedSql <- SqlRender::readSql(inputFile)

    renderedSql <- SqlRender::renderSql(parameterizedSql, cdmSchema = parameter$cdmSchema, ...)$sql

    translatedSql <- SqlRender::translateSql(renderedSql, targetDialect=dbms)$sql

    SqlRender::writeSql(translatedSql, outputFile)

    writeLines(paste("Created file '", outputFile, "'", sep = ""))

    outputFile
}
